# Generated by Django 4.2.2 on 2024-11-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('blocking_users', 'Can block users'), ('view_all_users', 'Can view all users'), ('unblocking_users', 'Can unblock users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
