# Generated by Django 5.1.2 on 2024-10-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'status', 'start_time', 'recipients'], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', related_query_name='messages', to='mailings.message'),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing', related_query_name='mailings', to='mailings.mailing'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', related_query_name='recipients', to='mailings.recipient'),
        ),
    ]
