# Generated by Django 5.1.2 on 2024-10-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailing_options_remove_mailing_recipients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'start_time', 'status', 'start_time'], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
