# Generated by Django 5.1.2 on 2024-10-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'start_time', 'status'], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(default='Создана', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', related_query_name='attempts', to='mailings.mailing'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
