# Generated by Django 5.1.2 on 2024-11-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailingattempt_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'start_time', 'status', 'views_count'], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество рассылок', verbose_name='Количество рассылок'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Введите наименование сообщения', max_length=100, null=True, verbose_name='Наименование сообщения')),
                ('body', models.TextField(blank=True, help_text='Введите текст сообщения', null=True, verbose_name='Текст сообщения')),
                ('status', models.CharField(max_length=50)),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='mailings.mailing', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Родительский сообщение',
                'verbose_name_plural': 'Родительские сообщения',
                'ordering': ['mailing', 'subject', 'body', 'status'],
            },
        ),
    ]
