# Generated by Django 4.2.2 on 2024-11-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0009_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'start_time', 'status', 'views_count', 'owner'], 'permissions': [('blocking_users', 'Can block users'), ('disabling_mailing', 'Can disable mailing'), ('viewing_statistics', 'Can viewing statistics')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
