# Generated by Django 4.2.2 on 2024-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0011_alter_mailing_options_alter_mailing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mail_active',
            field=models.BooleanField(default=True, verbose_name='Активность рассылки'),
        ),
    ]
