# Generated by Django 4.2.2 on 2024-11-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0013_alter_recipient_options_recipient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id', 'start_time', 'status', 'views_count', 'owner'], 'permissions': [('disabling_mailing', 'Can disable mailing'), ('blocking_users', 'Can block users'), ('viewing_statistics', 'Can viewing statistics')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
