# Generated by Django 4.2.2 on 2024-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0016_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='from_email',
            field=models.EmailField(default='default-email@example.com', help_text='Укажите адрес электронной почты отправителя.', max_length=254, verbose_name='Адрес отправителя'),
        ),
    ]
