# Generated by Django 4.2.2 on 2024-11-06 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0016_mailing_mailing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
