# Generated by Django 4.2.2 on 2024-11-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0017_mailingattempt_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', related_query_name='recipients', to='mailings.recipient'),
        ),
    ]
