# Generated by Django 4.2.2 on 2024-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0018_mailingattempt_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='recipients',
            field=models.ManyToManyField(related_name='Клиент', to='mailings.recipient', verbose_name='Клиент'),
        ),
    ]
