# Generated by Django 4.2.2 on 2024-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0019_remove_mailingattempt_recipients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='recipients',
        ),
    ]
