# Generated by Django 4.2.2 on 2024-11-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0021_mailingattempt_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='recipients',
        ),
    ]
