# Generated by Django 4.2.2 on 2024-11-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0022_remove_mailingattempt_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject', 'owner'], 'permissions': [('manager_view_message', 'Can manager view message')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Укажите владельца рассылки', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=50),
        ),
    ]
