# Generated by Django 4.2.2 on 2024-11-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0023_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject', 'owner'], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
    ]
