# Generated by Django 4.2.2 on 2024-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0025_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50),
        ),
    ]
